version: '3.8'

services:
  app:
    image: analytics-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.compose
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yaml
    networks:
      - analytics_network
  db_service:
    image: timescale/timescaledb:latest-pg17
    env_file:
      - .env.compose
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - analytics_network
volumes:
  timescaledb_data:
networks:
  analytics_network:
    driver: bridge